export enum UserDetailsActionType {
  FETCH_USER_DETAILS = 'userDetails::FETCH_USER_DETAILS',
  FETCH_USER_DETAILS_SUCCESS = 'userDetails::FETCH_USER_DETAILS_SUCCESS',
  FETCH_USER_DETAILS_FAILURE = 'userDetails::FETCH_USER_DETAILS_FAILURE'
}
