export enum UserDetailsActionType {
  CHANGE_USER_NAME = 'userDetails::CHANGE_USER_NAME',
  FETCH_USER_DETAILS = 'userDetails::FETCH_USER_DETAILS',
  FETCH_USER_DETAILS_SUCCESS = 'userDetails::FETCH_USER_DETAILS_SUCCESS',
  FETCH_USER_DETAILS_FAILURE = 'userDetails::FETCH_USER_DETAILS_FAILURE'
}
